[package]
name = "chip8asm"
version = "0.1.0"
authors = ["shepgoba"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
opt-level = 's'  # Optimize for size.
panic = 'abort'
lto = true